import { Box, Divider, Flex, useColorModeValue } from '@chakra-ui/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useCallback, useMemo } from 'react'
import { useBoard } from '../../../hooks/board'
import BoardApplications from '../BoardApplications'
import BoardHeader from '../BoardHeader'
import BoardTaskBody from './BoardTaskBody'
import BoardTaskName from './BoardTaskName'

export default function BoardTaskDetail() {
  const { userId, applicationId, taskId, getTask } = useBoard()
  const task = useMemo(() => getTask(taskId), [taskId])

  if (!task) {
    return <></>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" backgroundColor={useColorModeValue('blue.100', undefined)}>
        <BoardHeader />
        <Flex>
          <BoardApplications />
          <Box p={4} width="100%">
            <Box mb={4}>
              <BoardTaskName />
            </Box>

            <Divider borderColor={useColorModeValue('gray.700', 'gray.200')} />

            <Box
              background={useColorModeValue('white', 'gray.900')}
              borderRadius={10}
              maxWidth={700}
              mt={4}
              p={4}
            >
              <BoardTaskBody />
            </Box>
          </Box>
        </Flex>
      </Box>
    </>
  )
}
